"""add_multi_store_support

Revision ID: f1627b613e04
Revises: c2f7f2a1e9b4
Create Date: 2026-04-19 20:37:29.609132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect, text


# revision identifiers, used by Alembic.
revision = 'f1627b613e04'
down_revision = 'c2f7f2a1e9b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if stores table already exists
    conn = op.get_bind()
    inspector = inspect(conn)
    
    if 'stores' not in inspector.get_table_names():
        op.create_table('stores',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('code', sa.String(length=20), nullable=False),
        sa.Column('address', sa.String(length=255), nullable=True),
        sa.Column('phone', sa.String(length=30), nullable=True),
        sa.Column('email', sa.String(length=120), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
        )
    
    if 'store_settings' not in inspector.get_table_names():
        op.create_table('store_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('store_id', sa.Integer(), nullable=False),
        sa.Column('delivery_base_fee', sa.Integer(), nullable=True),
        sa.Column('free_shipping_min', sa.Integer(), nullable=True),
        sa.Column('delivery_eta', sa.String(length=50), nullable=True),
        sa.Column('same_day_delivery', sa.Boolean(), nullable=True),
        sa.Column('payment_cod', sa.Boolean(), nullable=True),
        sa.Column('payment_bank', sa.Boolean(), nullable=True),
        sa.Column('payment_card', sa.Boolean(), nullable=True),
        sa.Column('payment_ewallet', sa.Boolean(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    
    if 'store_staff' not in inspector.get_table_names():
        op.create_table('store_staff',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('store_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('assigned_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('store_id'),
        sa.UniqueConstraint('store_id', name='uq_store_one_staff'),
        sa.UniqueConstraint('user_id')
        )
    
    # Add store_id columns to existing tables using raw SQL (more robust for SQLite)
    inspector = inspect(conn)
    
    # Add store_id to admin_todos if it doesn't exist
    if 'store_id' not in [c['name'] for c in inspector.get_columns('admin_todos')]:
        try:
            conn.execute(text('ALTER TABLE admin_todos ADD COLUMN store_id INTEGER REFERENCES stores(id)'))
        except:
            pass

    # Add store_id to orders if it doesn't exist
    if 'store_id' not in [c['name'] for c in inspector.get_columns('orders')]:
        try:
            conn.execute(text('ALTER TABLE orders ADD COLUMN store_id INTEGER NOT NULL DEFAULT 1 REFERENCES stores(id)'))
        except:
            pass

    # Add store_id to product_batches if it doesn't exist
    if 'store_id' not in [c['name'] for c in inspector.get_columns('product_batches')]:
        try:
            conn.execute(text('ALTER TABLE product_batches ADD COLUMN store_id INTEGER NOT NULL DEFAULT 1 REFERENCES stores(id)'))
        except:
            pass

    # Add store_id to products if it doesn't exist
    if 'store_id' not in [c['name'] for c in inspector.get_columns('products')]:
        try:
            conn.execute(text('ALTER TABLE products ADD COLUMN store_id INTEGER NOT NULL DEFAULT 1 REFERENCES stores(id)'))
        except:
            pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('store_id')

    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_reviews_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_reviews_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('product_batches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_product_batches_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_batches_expiry_date'), ['expiry_date'], unique=False)
        batch_op.drop_column('store_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('store_id')

    with op.batch_alter_table('admin_todos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('store_id')

    op.drop_table('store_staff')
    op.drop_table('store_settings')
    op.drop_table('stores')
    # ### end Alembic commands ###
